
schema = {
    "months_as_customer": "int",
    "age": "int",
    "policy_number": "str",
    "policy_bind_date": "date",
    "policy_state": "str",
    "policy_csl": "str",
    "policy_deductable": "int",
    "policy_annual_premium": "float",
    "umbrella_limit": "int",
    "insured_zip": "str",
    "insured_sex": "str",
    "insured_education_level": "str",
    "insured_occupation": "str",
    "insured_hobbies": "str",
    "insured_relationship": "str",
    "capital-gains": "int",
    "capital-loss": "int",
    "incident_date": "date",
    "incident_type": "str",
    "collision_type": "str",
    "incident_severity": "str",
    "authorities_contacted": "str",
    "incident_state": "str",
    "incident_city": "str",
    "incident_location": "str",
    "incident_hour_of_the_day": "int",
    "number_of_vehicles_involved": "int",
    "property_damage": "str",
    "bodily_injuries": "int",
    "witnesses": "int",
    "police_report_available": "str",
    "total_claim_amount": "float",
    "injury_claim": "float",
    "property_claim": "float",
    "vehicle_claim": "float",
    "auto_make": "str",
    "auto_model": "str",
    "auto_year": "int",
    "fraud_reported": "str",
    "_c39": "str"
}

processed_schema = {
    "age": "int",
    "policy_state": "string",
    "policy_deductable": "int",
    "policy_annual_premium": "float",
    "umbrella_limit": "int",
    "insured_sex": "string",
    "insured_education_level": "string",
    "insured_occupation": "string",
    "insured_hobbies": "string",
    "insured_relationship": "string",
    "capital-gains": "int",
    "capital-loss": "int",
    "incident_type": "string",
    "collision_type": "string",
    "incident_severity": "string",
    "authorities_contacted": "string",
    "incident_state": "string",
    "incident_city": "string",
    "incident_hour_of_the_day": "int",
    "number_of_vehicles_involved": "int",
    "property_damage": "string",   # values: YES/NO/?
    "bodily_injuries": "int",
    "witnesses": "int",
    "police_report_available": "string",  # YES/NO/?
    "total_claim_amount": "int",
    "auto_make": "string",
    "auto_model": "string",
    "auto_year": "int",
    "fraud_reported": "string",   # Y/N
    "policy_bind_year": "int",
    "policy_bind_month": "int",
    "policy_bind_day": "int",
    "incident_date_year": "int",
    "incident_date_month": "int",
    "incident_date_day": "int",
    "csl_per_person": "int"
}